version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: mishramayankk20/nodejs-mysql-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=$DB_HOST
      - MYSQL_USER=$DB_USER
      - MYSQL_PASS=$DB_PASS
      - MYSQL_DB=$DB_NAME
    volumes:
      -  ./PROJECT_USER:/usr/src/app
    ports:
      - "30001:5000"
    container_name: nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
    container_name: mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpmyadmin-app
networks:
  frontend:
  backend: