apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
---      
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nodejs-deployment 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: nodejs 
  template: 
    metadata: 
      labels: 
        app: nodejs 
    spec: 
      containers:
      - name: nodeimage
        image: mishramayankk20/nodejs-final:2020
        ports: 
        - containerPort: 5000
    
